---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: develop

jobs:
  - name: job-hello-world
    plan:
      - get: resource-tutorial # gets the resource
      - task: hello-world
        # uses the resource to run the task:
        file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
